const Q=[
// Accounts & Passwörter
{a:11,c:'Accounts & Passwörter',d:'Basic',q:'Welches Passwort-Konzept ist am sichersten?',o:['Ein sehr langes Passwort, das ich überall benutze','Für jeden wichtigen Account ein eigenes langes Passwort','Mein Geburtsdatum plus mein Name','Ein kompliziertes Passwort, das ich meinen Freunden sage'],k:[1],p:2},
{a:11,c:'Accounts & Passwörter',d:'Advanced',q:'Du bekommst eine Login-Bestätigung für einen Account, obwohl du dich nicht angemeldet hast. Was ist die beste Reaktion?',o:['Ignorieren','Bestätigung anklicken, um nachzusehen','Direkt über die offizielle App/Website Passwort ändern und aktive Sitzungen prüfen','Den Code einem Freund schicken'],k:[2],p:3,rf:[0,1,3]},
{a:11,c:'Accounts & Passwörter',d:'Trap',q:'Was schützt ein Account am besten?',o:['HTTPS allein','Zwei-Faktor-Authentifizierung plus einzigartiges Passwort','Ein geheimes Profilbild','Ein langer Benutzername'],k:[1],p:2},
{a:13,c:'Accounts & Passwörter',d:'Expert',q:'Dein E-Mail-Passwort wurde auf einer Fake-Seite eingegeben und du benutzt es auch bei Steam und Instagram. Was sicherst du zuerst?',o:['Instagram, weil dort die meisten Follower sind','E-Mail, dann alle wiederverwendeten Accounts','Steam, weil dort Geld steckt','Nur den Fake-Link melden'],k:[1],p:4,rf:[0,2,3]},
{a:13,c:'Accounts & Passwörter',d:'Advanced',q:'Ein Passwortmanager meldet ein geleaktes Passwort. Was bedeutet das?',o:['Der Passwortmanager wurde gehackt','Das Passwort ist in bekannten Leak-Daten aufgetaucht und sollte geändert werden','Nur die Website ist unsicher, das Passwort kann bleiben','Man muss sofort den Account löschen'],k:[1],p:3},

// Phishing & Scams
{a:11,c:'Phishing & Scams',d:'Basic',q:'Ein Freund schickt dir unerwartet einen Link zu „kostenlosen Skins“. Was prüfst du zuerst?',o:['Ob viele Emojis in der Nachricht sind','Ob die Domain wirklich zur offiziellen Seite gehört und ob die Nachricht typisch für den Freund ist','Ob der Link kurz ist','Ob das Angebot nur heute gilt'],k:[1],p:3},
{a:11,c:'Phishing & Scams',d:'Trap',q:'Eine Webseite zeigt ein Schloss-Symbol und HTTPS. Ist sie deshalb sicher?',o:['Ja, immer','Nein. HTTPS schützt die Verbindung, sagt aber nicht, ob die Seite seriös ist','Nur auf dem Handy','Nur wenn Google sie anzeigt'],k:[1],p:3,rf:[0]},
{a:11,c:'Phishing & Scams',d:'Advanced',q:'Du bekommst: „Dein Account wird in 10 Minuten gesperrt! Jetzt anmelden.“ Was ist daran verdächtig?',o:['Zeitdruck','Drohung mit Verlust','Aufforderung zum Login','Alle drei'],k:[3],p:3},
{a:13,c:'Phishing & Scams',d:'Expert',q:'Welche Domain ist am ehesten verdächtig, wenn du dich bei Discord anmelden willst?',o:['discord.com','support.discord.com','discord-login-security.example','discord.com/login'],k:[2],p:3},
{a:13,c:'Phishing & Scams',d:'Expert',q:'Eine QR-Code-Karte verspricht gratis WLAN und öffnet eine Login-Seite. Was ist die sicherste Vorgehensweise?',o:['QR scannen und testen','Netzwerknamen und Zugang über eine offizielle Stelle prüfen','Nur E-Mail eingeben','VPN einschalten und dann alles eingeben'],k:[1],p:4},

// Fremde & Grooming
{a:11,c:'Fremde Personen & Grooming',d:'Advanced',q:'Eine Person im Spiel sagt, sie sei 12, schickt ein Selfie und kennt dieselben YouTuber wie du. Beweist das ihr Alter?',o:['Ja','Nein','Nur wenn das Bild echt aussieht','Nur nach einem Videoanruf'],k:[1],p:3},
{a:11,c:'Fremde Personen & Grooming',d:'Expert',q:'Jemand, den du nur online kennst, fragt nach deiner Schule. Was ist am besten?',o:['Schule nennen, aber nicht Klasse','Nicht nennen und bei Druck das Gespräch beenden/Vertrauensperson einbeziehen','Nur den Ort nennen','Erst seine Schule verlangen'],k:[1],p:4,rf:[0,2,3]},
{a:11,c:'Fremde Personen & Grooming',d:'Expert',q:'Eine Online-Bekanntschaft sagt: „Sag deinen Eltern nichts, die würden unsere Freundschaft nicht verstehen.“ Wie bewertest du das?',o:['Normal','Warnsignal, weil Geheimhaltung und Isolation aufgebaut werden','Nur peinlich','Okay, solange nichts Illegales passiert'],k:[1],p:4,rf:[0,3]},
{a:13,c:'Fremde Personen & Grooming',d:'Expert',q:'Eine Person droht, ein peinliches Bild zu verbreiten, wenn du kein weiteres schickst. Was ist die beste Reaktion?',o:['Noch eins schicken, damit Ruhe ist','Nicht weiter schicken, Beweise sichern, blockieren/melden und sofort Hilfe holen','Account löschen und niemandem erzählen','Zurückdrohen'],k:[1],p:5,rf:[0,2,3]},
{a:13,c:'Fremde Personen & Grooming',d:'Trap',q:'Ein Videoanruf zeigt scheinbar einen Jugendlichen. Ist die Identität damit sicher bestätigt?',o:['Ja','Nein, Video kann manipuliert oder die Situation inszeniert sein','Nur wenn die Stimme passt','Nur wenn die Person winkt'],k:[1],p:4},

// Chats & Social Engineering
{a:11,c:'Chats & Social Engineering',d:'Advanced',q:'Ein Admin eines Gaming-Servers fragt per DM nach deinem 2FA-Code. Was tust du?',o:['Schicken, Admins dürfen das','Nicht schicken; echte Support-Mitarbeiter brauchen keinen 2FA-Code','Nur die Hälfte schicken','Im Server öffentlich posten'],k:[1],p:4,rf:[0,2,3]},
{a:11,c:'Chats & Social Engineering',d:'Trap',q:'Welche Aussage ist richtig?',o:['Wenn eine Nachricht von einem Freund kommt, ist der Link sicher','Accounts von Freunden können übernommen werden','Sprachnachrichten können nie gefälscht werden','Bots dürfen Passwörter abfragen'],k:[1],p:3},
{a:13,c:'Chats & Social Engineering',d:'Expert',q:'Jemand ruft an, klingt wie dein Vater und bittet dringend um einen Code aus deiner SMS. Was ist am sichersten?',o:['Code nennen, weil die Stimme passt','Auflegen und über eine bekannte Nummer selbst zurückrufen','Nach dem Geburtsdatum fragen','Nur die letzten drei Ziffern nennen'],k:[1],p:5,rf:[0,2,3]},
{a:13,c:'Chats & Social Engineering',d:'Expert',q:'Welche Manipulation steckt in „Wenn du wirklich mein Freund bist, schickst du mir das“?',o:['Autorität','Sozialer Druck und Schuldgefühl','Knappheit','Technischer Betrug'],k:[1],p:3},

// Datenschutz & Standort
{a:11,c:'Datenschutz & Standort',d:'Basic',q:'Welche Info solltest du öffentlich am wenigsten teilen?',o:['Lieblingsfarbe','Schulname plus täglicher Schulweg','Lieblingsspiel','Lieblingsessen'],k:[1],p:3},
{a:11,c:'Datenschutz & Standort',d:'Advanced',q:'Warum können Fotos mehr verraten als man denkt?',o:['Dateien können Metadaten und sichtbare Ortsdetails enthalten','Fotos werden automatisch öffentlich','Jedes Foto enthält das Passwort','Kameras senden immer live den Standort'],k:[0],p:3},
{a:13,c:'Datenschutz & Standort',d:'Expert',q:'Du postest täglich um 7:15 ein Foto an derselben Bushaltestelle. Welches Risiko entsteht?',o:['Keins, wenn das Profil privat ist','Muster über Aufenthaltsort und Routine werden erkennbar','Nur die Kamera wird langsamer','Nur Werbung wird genauer'],k:[1],p:4},
{a:13,c:'Datenschutz & Standort',d:'Advanced',q:'Eine Taschenlampen-App verlangt Zugriff auf Kontakte, Mikrofon und Standort. Was ist sinnvoll?',o:['Alles erlauben','Nur Berechtigungen erlauben, die für die Funktion plausibel nötig sind','Kontakte erlauben, Rest nicht','App neu installieren'],k:[1],p:3},

// Fake News & KI
{a:11,c:'Fake News, KI & Deepfakes',d:'Advanced',q:'Ein TikTok behauptet: „Ab morgen darf WhatsApp alle Bilder verkaufen“. Was ist die beste Prüfung?',o:['Weiterleiten und Freunde fragen','Offizielle Quelle und seriöse Berichterstattung prüfen','Kommentare lesen','Auf die Anzahl Likes schauen'],k:[1],p:3},
{a:11,c:'Fake News, KI & Deepfakes',d:'Trap',q:'Ein Bild sieht extrem realistisch aus. Beweist das, dass das Ereignis wirklich passiert ist?',o:['Ja','Nein','Nur wenn es hochauflösend ist','Nur bei Nachtaufnahmen'],k:[1],p:3},
{a:13,c:'Fake News, KI & Deepfakes',d:'Expert',q:'Was ist bei einer überraschenden Sprachnachricht einer bekannten Person sinnvoll?',o:['Stimme sicher = echt','Kontext, Quelle und einen zweiten Kontaktweg prüfen','Nur die Lautstärke prüfen','Dateinamen prüfen'],k:[1],p:4},
{a:13,c:'Fake News, KI & Deepfakes',d:'Expert',q:'Welche Quelle ist für eine aktuelle Behauptung am stärksten?',o:['Ein Screenshot ohne Link','Ein anonymer Kommentar','Die Originalquelle plus mehrere unabhängige seriöse Berichte','Ein virales Reaction-Video'],k:[2],p:4},

// Cybermobbing
{a:11,c:'Cybermobbing & Gruppendruck',d:'Advanced',q:'In einer Klassengruppe wird ein peinliches Foto eines Mitschülers herumgeschickt. Was ist am besten?',o:['Weiterleiten, aber nur privat','Nicht weiterleiten, Unterstützung anbieten und bei Bedarf melden/Erwachsene einbeziehen','Mitlach-Emoji senden','Screenshot posten'],k:[1],p:4,rf:[0,2,3]},
{a:11,c:'Cybermobbing & Gruppendruck',d:'Trap',q:'Wenn du selbst nichts Beleidigendes schreibst, aber beleidigende Posts likest und weiterleitest, bist du völlig unbeteiligt.',o:['Richtig','Falsch'],k:[1],p:3},
{a:13,c:'Cybermobbing & Gruppendruck',d:'Expert',q:'Warum kann „Lösch einfach alles“ bei Cybermobbing problematisch sein?',o:['Weil Beweise verloren gehen können','Weil Handys langsamer werden','Weil Löschen verboten ist','Weil Screenshots nie helfen'],k:[0],p:4},
{a:13,c:'Cybermobbing & Gruppendruck',d:'Expert',q:'Was ist bei ernsthaften Drohungen online sinnvoll?',o:['Alleine lösen','Beweise sichern und sofort eine Vertrauensperson/geeignete Stelle einbeziehen','Zurückdrohen','Nur Account wechseln'],k:[1],p:5,rf:[0,2,3]},

// Downloads & Malware
{a:11,c:'Downloads, Mods & Malware',d:'Advanced',q:'Ein YouTube-Video verlinkt ein Programm für „Free Robux“. Was ist am sichersten?',o:['Starten, wenn viele Likes da sind','Nur aus vertrauenswürdiger Quelle laden und Datei/Quelle prüfen; unbekannte EXE eher nicht ausführen','Datei umbenennen','Im Inkognito-Modus starten'],k:[1],p:4},
{a:11,c:'Downloads, Mods & Malware',d:'Trap',q:'Welche Datei kann besonders riskant sein?',o:['urlaub.jpg','hausaufgabe.txt','setup.exe','musik.mp3'],k:[2],p:3},
{a:13,c:'Downloads, Mods & Malware',d:'Expert',q:'Ein Mod verlangt, den Virenscanner kurz auszuschalten. Wie bewertest du das?',o:['Normal bei Mods','Starkes Warnsignal','Nur bei kostenlosen Mods problematisch','Okay, wenn der Entwickler nett klingt'],k:[1],p:4,rf:[0,2,3]},
{a:13,c:'Downloads, Mods & Malware',d:'Advanced',q:'Was ist bei ZIP-Dateien wichtig?',o:['Sie sind immer sicher','Sie können ausführbare oder schädliche Dateien enthalten','Sie funktionieren nur offline','Antivirus kann sie nie prüfen'],k:[1],p:3},

// Geld & Käufe
{a:11,c:'Geld, Shops & In-App-Käufe',d:'Advanced',q:'Ein Shop bietet eine Konsole für 90 % weniger als überall sonst. Was ist sinnvoll?',o:['Sofort kaufen','Impressum, Bewertungen außerhalb des Shops, Zahlungsarten und Preisplausibilität prüfen','Nur das Logo prüfen','Nur mit Geschenkkarte zahlen'],k:[1],p:4},
{a:11,c:'Geld, Shops & In-App-Käufe',d:'Trap',q:'„Nur noch 2 Minuten!“ bei einem Kaufangebot ist vor allem…',o:['eine Garantie','Zeitdruck/Manipulation','ein Sicherheitsmerkmal','ein Altersnachweis'],k:[1],p:3},
{a:13,c:'Geld, Shops & In-App-Käufe',d:'Expert',q:'Warum sind Lootboxen problematisch?',o:['Sie können zufallsbasierte Belohnungsmechaniken und Gelddruck erzeugen','Weil Skins verboten sind','Weil Spiele dadurch offline gehen','Nur wegen Werbung'],k:[0],p:4},
{a:13,c:'Geld, Shops & In-App-Käufe',d:'Expert',q:'Jemand bietet dir an, deinen Gaming-Account gegen Geld „zu boosten“, braucht aber Login und 2FA. Was ist die beste Entscheidung?',o:['Machen, wenn er Bewertungen hat','Nicht geben; Zugangsdaten und 2FA nie herausgeben','Nur Passwort geben','Neuen Account erstellen und testen'],k:[1],p:4,rf:[0,2,3]},

// Notfälle
{a:11,c:'Notfälle & Hilfe holen',d:'Advanced',q:'Du hast versehentlich dein Passwort auf einer Fake-Seite eingegeben. Was jetzt?',o:['Nichts, wenn kein Fehler angezeigt wurde','Passwort über die echte Website ändern, Sitzungen prüfen und ggf. Hilfe holen','Browser löschen','Handy ausschalten'],k:[1],p:5,rf:[0,2,3]},
{a:11,c:'Notfälle & Hilfe holen',d:'Expert',q:'Was ist bei Erpressung mit Bildern besonders wichtig?',o:['Nicht weiter zahlen/senden und Hilfe holen','Alles geheim halten','Account sofort löschen und schweigen','Gegenmaterial sammeln und zurückerpressen'],k:[0],p:5,rf:[1,2,3]},
{a:13,c:'Notfälle & Hilfe holen',d:'Expert',q:'Ein Account wurde übernommen. Welche Reihenfolge ist sinnvoll?',o:['Passwort ändern → Sitzungen abmelden → 2FA prüfen → Recovery-Daten prüfen','Profilbild ändern → Freunde blockieren → App löschen','Neuen Account erstellen und alten ignorieren','Nur Support anschreiben'],k:[0],p:5},
{a:13,c:'Notfälle & Hilfe holen',d:'Trap',q:'Du hast Mist gebaut und schämst dich. Was ist die sicherste Grundregel?',o:['Je peinlicher, desto geheimer','Bei ernstem Risiko trotzdem früh Hilfe holen','Erst warten, ob es schlimmer wird','Nur anonym posten'],k:[1],p:5,rf:[0,2,3]},

// Recht & Verantwortung
{a:11,c:'Recht & Verantwortung',d:'Advanced',q:'Darfst du ein peinliches Foto eines Mitschülers einfach posten, wenn du es selbst gemacht hast?',o:['Ja, weil es dein Foto ist','Nein, Rechte und Privatsphäre der abgebildeten Person spielen eine Rolle','Ja, wenn es lustig ist','Nur nachts'],k:[1],p:3},
{a:13,c:'Recht & Verantwortung',d:'Expert',q:'Was gilt für Screenshots privater Chats?',o:['Immer frei teilbar','Kontext, Persönlichkeitsrechte und mögliche Folgen beachten; nicht einfach veröffentlichen','Nur mit Emoji erlaubt','Privatchats sind automatisch gemeinfrei'],k:[1],p:4},

// Freitext-Fälle
{a:11,c:'Praxisfälle',d:'Expert',q:'Fall: Verdächtige Nachricht',s:'Dein bester Freund schreibt plötzlich: „Bro schick mal schnell den Code, der gerade per SMS kommt, brauche den für mein neues Handy.“\n\nBeschreibe Schritt für Schritt, was du tun würdest und warum.',t:'free',p:5,manual:true},
{a:11,c:'Praxisfälle',d:'Expert',q:'Fall: Fremde Person im Game',s:'Du spielst seit zwei Wochen regelmäßig mit „Luca13“. Er ist nett, kennt dieselben Games und fragt jetzt nach deiner Schule und ob ihr euch mal treffen wollt.\n\nWelche Risiken siehst du? Was würdest du konkret tun?',t:'free',p:5,manual:true},
{a:11,c:'Praxisfälle',d:'Expert',q:'Fall: Virales Gerücht',s:'Ein virales Video behauptet, eine bekannte App würde ab morgen heimlich alle privaten Fotos veröffentlichen.\n\nWie würdest du in fünf Minuten prüfen, ob das stimmt?',t:'free',p:5,manual:true},
{a:13,c:'Praxisfälle',d:'Expert',q:'Fall: Account-Kompromittierung',s:'Du bemerkst, dass dein E-Mail-Account offen ist, obwohl du dich nicht eingeloggt hast. Dasselbe Passwort nutzt du bei drei weiteren Diensten.\n\nBeschreibe eine sinnvolle Reihenfolge deiner Maßnahmen.',t:'free',p:6,manual:true},
{a:13,c:'Praxisfälle',d:'Expert',q:'Fall: Sextortion / Erpressung',s:'Eine Person besitzt ein privates Bild und droht, es an Kontakte zu schicken. Sie verlangt weiteres Material oder Geld.\n\nWas solltest du tun, was ausdrücklich nicht und wen würdest du einbeziehen?',t:'free',p:6,manual:true},
{a:13,c:'Praxisfälle',d:'Expert',q:'Fall: Deepfake-Stimme',s:'Du bekommst einen Anruf. Die Stimme klingt exakt wie ein Familienmitglied und bittet dringend um einen SMS-Code.\n\nWie verifizierst du die Situation, ohne dich auf die Stimme zu verlassen?',t:'free',p:6,manual:true}
];

let age=11,items=[],i=0,answers={};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
$$('.mode').forEach(b=>b.onclick=()=>start(+b.dataset.age));
$('#prevBtn').onclick=()=>{save();if(i>0){i--;render()}};
$('#nextBtn').onclick=()=>{save();if(i<items.length-1){i++;render()}else finish()};
$('#restartBtn').onclick=()=>location.reload(); $('#printBtn').onclick=()=>print();
function start(a){age=a;items=Q.filter(x=>x.a<=a);$('#start').classList.add('hidden');$('#quiz').classList.remove('hidden');$('#modeLabel').textContent=a===11?'Junior · 11 Jahre':'Advanced · 13 Jahre';render()}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderVisual(v){
  const el=$('#visual'); el.innerHTML=''; el.classList.toggle('hidden',!v); if(!v)return;
  const bubble=(side,text,name='')=>`<div class="msg ${side}">${name?`<small>${esc(name)}</small>`:''}<span>${esc(text)}</span></div>`;
  if(v.type==='chat') el.innerHTML=`<div class="shot phone"><div class="shot-head"><div class="avatar">${esc((v.person||'?')[0])}</div><div><strong>${esc(v.person)}</strong><small>${esc(v.status||'')}</small></div><span class="shot-actions">◌  ⋯</span></div><div class="chat-body">${v.messages.map(m=>bubble(m[0]==='me'?'me':'them',m[1])).join('')}</div><div class="composer">Nachricht schreiben… <b>＋</b></div></div>`;
  if(v.type==='group') el.innerHTML=`<div class="shot group-shot"><div class="shot-head"><div class="avatar">#</div><div><strong>${esc(v.title)}</strong><small>Gruppenchat · Simulation</small></div></div><div class="chat-body">${v.messages.map(m=>bubble('them',m[1],m[0])).join('')}</div></div>`;
  if(v.type==='profile') el.innerHTML=`<div class="shot profile-shot"><div class="profile-top"><div class="profile-avatar">${esc(v.name[0].toUpperCase())}</div><div><strong>@${esc(v.name)}</strong><div class="profile-stats">24 Beiträge · 318 Follower</div></div><button type="button" tabindex="-1">Folgen</button></div><pre class="profile-bio">${esc(v.bio)}</pre><div class="post-grid">${v.posts.map((x,n)=>`<div class="post-card"><span>${['📸','📍','💬'][n%3]}</span><p>${esc(x)}</p></div>`).join('')}</div></div>`;
  if(v.type==='post') el.innerHTML=`<div class="shot post-shot"><div class="post-user"><div class="avatar">${esc(v.account[0].toUpperCase())}</div><div><strong>@${esc(v.account)}</strong><small>${v.verified?'Verifiziert':'öffentliches Profil'}</small></div></div><div class="post-text">${esc(v.text)}</div><div class="post-stats">♡ ${esc(v.stats)}</div></div>`;
  if(v.type==='voice') el.innerHTML=`<div class="shot voice-shot"><div class="shot-head"><div class="avatar">${esc(v.from[0])}</div><div><strong>${esc(v.from)}</strong><small>Sprachnachricht</small></div></div><div class="voice-line"><button type="button" tabindex="-1">▶</button><div class="wave">▂▅▇▃▆▂▇▅▃▆▂▅▇▃</div><span>${esc(v.duration)}</span></div><p>${esc(v.text)}</p></div>`;
  if(v.type==='support') el.innerHTML=`<div class="shot support-shot"><div class="support-brand"><div class="shield">✓</div><div><strong>${esc(v.brand)}</strong><small>Direktnachricht · Simulation</small></div></div><div class="chat-body">${v.messages.map(m=>bubble('them',m[1],m[0])).join('')}</div></div>`;
  if(v.type==='timeline') el.innerHTML=`<div class="shot timeline-shot"><div class="timeline-title">Verlauf der Online-Bekanntschaft</div>${v.steps.map(s=>`<div class="timeline-step ${esc(s[2])}"><b>${esc(s[0])}</b><span>${esc(s[1])}</span></div>`).join('')}</div>`;
  if(v.type==='combo') el.innerHTML=`<div class="combo-wrap"><div class="shot profile-shot mini"><div class="profile-top"><div class="profile-avatar">${esc(v.profile.name[0].toUpperCase())}</div><div><strong>@${esc(v.profile.name)}</strong><div class="profile-stats">öffentlich</div></div></div><pre class="profile-bio">${esc(v.profile.bio)}</pre><div class="post-grid">${v.profile.posts.map(x=>`<div class="post-card"><span>📍</span><p>${esc(x)}</p></div>`).join('')}</div></div><div class="shot phone mini"><div class="shot-head"><div class="avatar">${esc(v.chat.person[0])}</div><div><strong>${esc(v.chat.person)}</strong><small>Direktnachricht</small></div></div><div class="chat-body">${v.chat.messages.map(m=>bubble('them',m[1])).join('')}</div></div></div>`;
}
function render(){const x=items[i];$('#categoryTitle').textContent=x.c;$('#categoryTag').textContent=x.c;$('#difficulty').textContent=x.d;$('#questionText').textContent=x.q;$('#progressText').textContent=`${i+1} / ${items.length}`;$('#progressBar').style.width=((i+1)/items.length*100)+'%';$('#scenario').classList.toggle('hidden',!x.s);$('#scenario').textContent=x.s||'';renderVisual(x.v);$('#answers').innerHTML='';$('#freeWrap').classList.toggle('hidden',x.t!=='free');
if(x.t==='free'){$('#freeAnswer').value=answers[i]?.free||''}
else {const multi=x.t==='multi';x.o.forEach((o,n)=>{const l=document.createElement('label');l.className='answer';l.innerHTML=`<input type="${multi?'checkbox':'radio'}" name="q" value="${n}"><span>${esc(o)}</span>`;$('#answers').appendChild(l)});if(multi){(answers[i]?.choices||[]).forEach(n=>{const el=$(`input[name="q"][value="${n}"]`);if(el)el.checked=true})}else if(answers[i]?.choice!=null){const el=$(`input[name="q"][value="${answers[i].choice}"]`);if(el)el.checked=true}}
$('#prevBtn').disabled=i===0;$('#nextBtn').textContent=i===items.length-1?'Auswerten':'Weiter'}
function save(){const x=items[i];if(x.t==='free'){answers[i]={free:$('#freeAnswer').value.trim()}}else if(x.t==='multi'){answers[i]={choices:$$('input[name="q"]:checked').map(e=>+e.value)}}else{const c=$('input[name="q"]:checked');answers[i]={choice:c?+c.value:null}}}
function multiPoints(x,a){const selected=new Set(a?.choices||[]), correct=new Set(x.k||[]);if(!selected.size)return 0;let good=0,bad=0;selected.forEach(n=>correct.has(n)?good++:bad++);const ratio=Math.max(0,(good-bad)/Math.max(1,correct.size));return Math.round(x.p*ratio)}
function finish(){save();$('#quiz').classList.add('hidden');$('#result').classList.remove('hidden');let got=0,max=0,rf=[],cats={};items.forEach((x,idx)=>{max+=x.p;cats[x.c]??={g:0,m:0};cats[x.c].m+=x.p;const a=answers[idx];let pts=0;if(x.manual){pts=a?.free?.length>=120?Math.round(x.p*.75):a?.free?.length>=70?Math.round(x.p*.55):a?.free?.length>=30?Math.round(x.p*.3):0}else if(x.t==='multi'){pts=multiPoints(x,a);if(x.rf&&(a?.choices||[]).some(c=>x.rf.includes(c)))rf.push(`${x.c}: ${x.q}`)}else if(a?.choice!=null){if(x.k.includes(a.choice))pts=x.p;else if(x.rf?.includes(a.choice))rf.push(`${x.c}: ${x.q}`)}got+=pts;cats[x.c].g+=pts});
const pct=Math.round(got/max*100);$('#scoreTitle').textContent=`${pct}% · ${level(pct)}`;$('#scoreIntro').textContent=`Automatisch bewertet: ${got} von ${max} Punkten. Mehrfachauswahl wird anteilig bewertet. Freitext-Aufgaben werden nur grob nach Bearbeitungstiefe bewertet und sollten gemeinsam nachbesprochen werden.`;$('#categoryScores').innerHTML=Object.entries(cats).map(([k,v])=>{const p=Math.round(v.g/v.m*100);return `<div class="score-row"><strong>${esc(k)}</strong><div class="meter"><i style="width:${p}%;--score:${p}%"></i></div><span>${p}%</span></div>`}).join('');$('#redFlags').innerHTML=rf.length?`<h2>Kritische Red Flags</h2>${rf.map(x=>`<div class="flag">${esc(x)}</div>`).join('')}`:'<h2>Keine kritischen Red Flags erkannt</h2><p>Das heißt nicht, dass alle Bereiche sicher sitzen – schaut zusätzlich auf schwache Kategorien und Freitext-Begründungen.</p>';scrollTo(0,0)}
function level(p){if(p>=90)return'Extrem stark';if(p>=80)return'Sehr sicher';if(p>=70)return'Fortgeschritten';if(p>=55)return'Grundsätzlich solide';return'Deutlicher Übungsbedarf'}
