// Social Interaction Pack v0.2 – additional age-appropriate scenarios.
// Loaded after app.js; pushes extra questions into the existing Q array.
Q.push(
{a:11,c:'Fremde Personen & Grooming',d:'Advanced',q:'Eine neue Online-Bekanntschaft schreibt dir jeden Abend. Nach ein paar Tagen sagt sie: „Du kannst mir alles erzählen. Deine Eltern verstehen dich bestimmt sowieso nicht so gut wie ich.“ Was ist daran am ehesten auffällig?',o:['Dass die Person oft online ist','Dass sie versucht, sich als wichtigste Vertrauensperson darzustellen und andere Bezugspersonen abzuwerten','Dass sie nett zu dir ist','Dass sie abends schreibt'],k:[1],p:4},
{a:11,c:'Fremde Personen & Grooming',d:'Expert',q:'Jemand aus deinem Game möchte zu einem privaten Chat wechseln, „damit die nervigen Mods nichts mitlesen“. Wie reagierst du am sinnvollsten?',o:['Ich wechsle sofort, private Chats sind grundsätzlich sicherer','Ich bleibe vorsichtig; der Wunsch nach unbeobachteter Kommunikation kann ein Warnsignal sein und ich muss nicht wechseln','Ich wechsle, aber lösche den Verlauf danach','Ich gebe zuerst meine Handynummer, damit ich weiß, wer die Person ist'],k:[1],p:4,rf:[2,3]},
{a:11,c:'Fremde Personen & Grooming',d:'Expert',q:'Eine Online-Bekanntschaft macht dir häufig Geschenke im Spiel und sagt später: „Jetzt kannst du mir aber auch mal einen Gefallen tun.“ Welche Antwort ist am besten?',o:['Ich schulde der Person etwas, weil sie Geld für mich ausgegeben hat','Geschenke verpflichten mich zu nichts; bei unangenehmen Forderungen sage ich Nein und hole mir Unterstützung','Ich mache einen kleinen Gefallen, damit es fair bleibt','Ich frage, wie teuer die Geschenke waren, und entscheide danach'],k:[1],p:5,rf:[0,2,3]},
{a:11,c:'Chats & Social Engineering',d:'Advanced',q:'In einer Gruppe schreibt jemand: „Alle anderen haben ihr Gesicht schon gezeigt. Sei nicht so langweilig.“ Was ist die stärkste Reaktion?',o:['Ein Foto schicken, auf dem nur ein Teil meines Gesichts zu sehen ist','Nicht aus Gruppendruck etwas teilen; ich entscheide selbst, welche Bilder ich verschicke','Erst warten, bis noch mehr Leute Fotos schicken','Ein altes Foto schicken, damit die Gruppe zufrieden ist'],k:[1],p:4},
{a:11,c:'Notfälle & Hilfe holen',d:'Expert',q:'Du hast einer Online-Person bereits etwas Persönliches erzählt und merkst danach, dass das vielleicht keine gute Idee war. Was ist jetzt sinnvoll?',o:['Nichts sagen, sonst bekomme ich bestimmt Ärger','Kontakt begrenzen und einer vertrauenswürdigen erwachsenen Person erzählen, was passiert ist','Alles löschen und so tun, als wäre nichts passiert','Der Person noch mehr erzählen, damit sie mir vertraut und nichts weitererzählt'],k:[1],p:5,rf:[0,2,3]},
{a:13,c:'Fremde Personen & Grooming',d:'Expert',q:'Eine Person, die du online kennengelernt hast, wird über Wochen immer vertrauter. Sie fragt zunächst nach Hobbys, später nach Streit zu Hause und sagt schließlich: „Bei mir kannst du wenigstens ehrlich sein.“ Was solltest du besonders beachten?',o:['Lange Bekanntschaft bedeutet automatisch, dass die Person vertrauenswürdig ist','Vertrauen kann gezielt und langsam aufgebaut werden; persönliche Verletzlichkeiten sollte ich nicht als Identitätsbeweis oder Sicherheitsgarantie behandeln','Solange die Person keine Links sendet, gibt es kein relevantes Risiko','Wenn wir dieselben Probleme haben, kann ich davon ausgehen, dass sie wirklich gleich alt ist'],k:[1],p:5},
{a:13,c:'Fremde Personen & Grooming',d:'Expert',q:'Eine Online-Bekanntschaft möchte dich treffen. Welche Vorgehensweise ist am sichersten?',o:['Allein an einem öffentlichen Ort treffen, weil dort andere Menschen sind','Nicht heimlich oder allein treffen; vorher eine Vertrauensperson einbeziehen und Identität sowie Rahmen gemeinsam prüfen','Die Person zuerst zu dir nach Hause einladen, damit du die Umgebung kennst','Nur einem Freund schreiben, wo du bist, aber Erwachsenen nichts sagen'],k:[1],p:5,rf:[0,2,3]},
{a:13,c:'Fremde Personen & Grooming',d:'Trap',q:'Eine Person hat dir über Monate nie etwas Sexuelles geschrieben und war immer hilfsbereit. Bedeutet das, dass spätere Grenzüberschreitungen kein Grooming sein können?',o:['Ja, Grooming beginnt immer sofort mit sexuellen Nachrichten','Nein; problematisches Vertrauen und Abhängigkeit können schrittweise aufgebaut werden','Ja, wenn ihr schon länger als drei Monate schreibt','Nur dann, wenn die Person nachweislich erwachsen ist'],k:[1],p:5},
{a:13,c:'Chats & Social Engineering',d:'Expert',q:'Ein enger Online-Freund reagiert beleidigt, weil du eine persönliche Frage nicht beantworten willst: „Krass, ich dachte, du vertraust mir.“ Was ist die beste Einschätzung?',o:['Ich sollte antworten, sonst zerstöre ich die Freundschaft','Meine Grenze bleibt gültig; Schuldgefühle zu erzeugen, um Informationen zu bekommen, ist problematischer Druck','Ich sollte eine weniger genaue Antwort erfinden','Ich muss die Person sofort überall blockieren, egal was vorher passiert ist'],k:[1],p:4},
{a:13,c:'Fremde Personen & Grooming',d:'Expert',q:'Eine Online-Person bittet um ein privates Bild und verspricht: „Ich speichere es nicht, Ehrenwort.“ Welche Überlegung ist am wichtigsten?',o:['Ein Versprechen reicht, wenn ich die Person lange kenne','Nach dem Versenden verliere ich Kontrolle darüber, ob kopiert, gespeichert oder weitergegeben wird','Wenn die Nachricht auf „einmal ansehen“ steht, kann technisch nichts gespeichert werden','Wenn die Person zuerst ein eigenes Bild sendet, ist der Austausch fair und sicher'],k:[1],p:5,rf:[0,2,3]},
{a:13,c:'Cybermobbing & Gruppendruck',d:'Expert',q:'Ein Freund erzählt dir privat, dass er online erpresst wird, und verlangt: „Versprich, dass du es keinem Erwachsenen sagst.“ Was ist die beste Reaktion?',o:['Das Versprechen unbedingt halten, egal wie gefährlich es wird','Ernst nehmen, bei akuter Gefahr Unterstützung holen und dem Freund erklären, warum Hilfe wichtiger als Geheimhaltung ist','Selbst mit dem Erpresser verhandeln','Den Chat in der Klassengruppe posten, damit alle helfen können'],k:[1],p:5,rf:[0,2,3]},
{a:13,c:'Praxisfälle',d:'Expert',q:'Fall: Langsamer Vertrauensaufbau',s:'Seit sechs Wochen spielst du fast täglich mit „Mika14“. Mika hört dir bei Problemen zu, schenkt dir gelegentlich In-Game-Sachen und schreibt inzwischen lieber privat. Eines Abends sagt Mika, deine Eltern würden eure Freundschaft wahrscheinlich verbieten und deshalb solltet ihr ihnen nichts erzählen. Kurz danach fragt Mika nach einem privaten Foto.\n\nNenne möglichst viele einzelne Warnsignale. Erkläre außerdem, welche davon allein noch harmlos sein könnten und warum die Kombination trotzdem wichtig ist. Beschreibe anschließend deine nächsten Schritte.',t:'free',p:8,manual:true},
{a:11,c:'Praxisfälle',d:'Expert',q:'Fall: Freundschaft oder Druck?',s:'Du kennst jemanden aus einem Spiel seit drei Wochen. Die Person ist meistens nett, schreibt aber immer öfter: „Warum antwortest du nicht?“, „Mit wem spielst du gerade?“ und „Wenn wir echte Freunde sind, gibst du mir deine Nummer.“\n\nWas davon findest du normal, was unangenehm oder riskant? Begründe deine Einschätzung und beschreibe, wie du Grenzen setzen würdest.',t:'free',p:7,manual:true}
);
